version: "3.9"

services:
  hsrh-database:
    image: postgres:12-alpine
    container_name: hsrh-database
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=qwoihe89231hdd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=starrail
    volumes:
      - ./postgres-data:/var/lib/postgesql/data

  hsrh-backend:
    restart: always
    build: ./server
    container_name: hsrh-backend
    links:
      - "hsrh-database:database"
    expose:
      - "8080"
    hostname: backend
    depends_on:
      - hsrh-database
    command: bash -c "npm run migration:run && node dist/main.js"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=qwoihe89231hdd
      - DATABASE_NAME=starrail
      - JWT_SECRET=oidfhs98sdfhsf

  hsrh-frontend:
    restart: always
    build: ./client
    container_name: hsrh-frontend
    depends_on:
      - hsrh-backend
    links:
      - "hsrh-backend:backend"
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:8080
